name: dynamic_domain
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  plugin_platform_interface: ^2.0.2
  path_provider: 2.0.11 # 使用最稳定的非 Pigeon 版本
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.dynamic_domain
        pluginClass: DynamicDomainPlugin
      ios:
        pluginClass: DynamicDomainPlugin

  assets:
    - assets/geoip.dat
    - assets/geosite.dat
