name: openim_common
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  get: ^4.6.5
  dio: ^5.7.0
  talker_dio_logger: ^4.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.18
  sprintf: ^7.0.0
  uuid: ^4.2.1
  path_provider: ^2.0.13
  #  android_path_provider: ^0.3.0
  image_picker: ^1.0.4
  flutter_easyloading: ^3.0.5
  azlistview: ^2.0.0
  lpinyin: ^2.0.3
  rxdart: ^0.27.7
  permission_handler: ^11.0.1
  wechat_assets_picker:
  wechat_camera_picker:
  extended_image: ^8.2.0
  country_picker: ^2.0.20
  file_picker: ^8.0.6
  open_filex: ^4.3.2
  lottie: 3.3.1
  mobile_scanner: 7.0.1
  qr_flutter: ^4.0.0
  image_cropper: 10.0.0+1
  package_info_plus: ^8.0.2
  search_keyword_text: ^0.0.2
  animated_text_kit: ^4.2.2
  flutter_local_notifications: ^19.4.2
  # flutter_app_badger: ^1.5.0
  app_badge_plus: ^1.2.3
  crypto: ^3.0.2
  url_launcher: ^6.1.10
  common_utils: ^2.1.0
  map_launcher: ^3.1.0
  flutter_spinkit: ^5.1.0
  percent_indicator: ^4.2.3
  flutter_image_compress: ^2.1.0
  font_awesome_flutter: ^9.1.1
  dart_date: ^1.1.1
  video_compress: ^3.1.2
  just_audio: ^0.9.31
  # flutter_inappwebview: ^5.8.0
  vibration: ^3.1.3
  scroll_to_index: ^3.0.1
  flutter_screen_lock: ^9.0.1
  local_auth: ^2.2.0
  sound_mode: 3.1.1
  device_info_plus: ^10.1.2
  visibility_detector: ^0.4.0+2
  extended_text_field: ^16.0.0
  extended_text: ^14.0.0
  animate_do: ^3.0.2
  should_rebuild: ^1.0.1
  record: ^6.0.0
  mime: ^1.0.4
  flutter_keyboard_visibility: ^6.0.0
  rotated_corner_decoration: ^2.1.0
  chewie: 1.7.0
  video_player: ^2.9.1
  flutter_cache_manager: ^3.3.0
  syncfusion_flutter_core: ^28.1.38
  syncfusion_flutter_sliders: ^28.1.38
  
  # ffmpeg_kit_flutter_full_gpl:
  #   path:  ../local_plugin/ffmpeg_kit_flutter_full_gpl
  pull_to_refresh_new: ^2.0.5
  intl: ^0.20.2

  flutter_download_manager:
    path: ../local_plugin/flutter_download_manager
  photo_browser:
    path: ../local_plugin/photo_browser
  # flutter_inappwebview:
  #   path: ../local_plugin/flutter_inappwebview
  flutter_picker_plus: ^1.1.3
  # flutter_openim_sdk: 3.8.1
  # flutter_openim_sdk: ^3.8.3+3
  flutter_openim_sdk:
    path: ../local_plugin/flutter_openim_sdk

  dynamic_domain:
    path: ../local_plugin/DynamicDomainSDK
  # marquee 2.3.0版本对flutter的最低版本要求是3.5，
  marquee: ^2.2.03
  connectivity_plus: ^6.1.3
  flutter_staggered_animations: ^1.1.1
  ionicons: ^0.2.2
  google_fonts: ^6.2.1
  chat_bottom_container: ^0.3.2
  emoji_selector:
    path: ../flutter-emoji-selector
  cupertino_icons: ^1.0.8
  image_gallery_saver_plus: ^4.0.1
  ffmpeg_kit_flutter_new: ^3.2.0
  flutter_inappwebview: ^6.1.5


dependency_overrides:
  # marquee ^2.2.03版本使用的fading_edge_scrollview是3.0.0，和当前flutter版本3.22.3不兼容 所以要dependency_overrides，
  fading_edge_scrollview: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/anim/
    - assets/audio/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
